name: portfolio
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  custom_fade_animation:
  google_fonts:
  splashscreen:
  flutter_native_splash:
  get:
  get_storage:
  http:
  carousel_slider:
  curved_navigation_bar:
  webview_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/